/**
 * One-shot generator: fetch the Gen-1 species catalog from PokeAPI and
 * write model/seed/species.ts — the rows that seed the `pokemon` table.
 * The mirror of scripts/download-icons.ts (run: npm run seed:species).
 *
 * For each dexId 1..151 it takes the official English name (PokeAPI's
 * localized `names` keep the real spelling: Farfetch'd, Nidoran♀,
 * Mr. Mime), the first English flavor text as the description, the modern
 * type set (what the current games and Pokémon GO show — PokeAPI types
 * are always current, never the Gen-1 originals) and the size in PokeAPI
 * raw units.
 * The extension itself never talks to the network — this runs once,
 * while developing, and its output is committed like the icons.
 */

import { mkdir, writeFile } from 'node:fs/promises';

const SPECIES_BASE = 'https://pokeapi.co/api/v2/pokemon-species';
const POKEMON_BASE = 'https://pokeapi.co/api/v2/pokemon';
const OUT_FILE = 'model/seed/species.ts';
const FIRST_ID = 1;
const LAST_ID = 151;
const RETRIES = 3;

/** The slice of a PokeAPI pokemon-species response this script needs. */
interface SpeciesJson {
  names: { name: string; language: { name: string } }[];
  flavor_text_entries: { flavor_text: string; language: { name: string } }[];
}

/** The slice of a PokeAPI pokemon response this script needs. The types are
 *  the modern set (slot order) — the current games' and Pokémon GO's, not
 *  the Gen-1 originals (Magnemite is electric/steel, not electric). */
interface PokemonJson {
  types: { slot: number; type: { name: string } }[];
  height: number; // decimeters
  weight: number; // hectograms
}

interface SeedRow {
  dexId: number;
  name: string;
  description: string;
  /** Modern type slugs, primary first (PokeAPI slot order). */
  types: string[];
  height: number; // decimeters
  weight: number; // hectograms
}

try {
  const rows: SeedRow[] = [];

  for (let id = FIRST_ID; id <= LAST_ID; id++) {
    const [species, poke] = await Promise.all([
      fetchSpecies(id),
      fetchPokemon(id),
    ]);

    const englishName = species.names.find((n) => n.language.name === 'en');
    if (!englishName)
      throw new Error(`#${id}: no English name in the response`);

    const englishText = species.flavor_text_entries.find(
      (e) => e.language.name === 'en',
    );
    if (!englishText)
      throw new Error(`#${id}: no English flavor text in the response`);

    rows.push({
      dexId: id,
      name: englishName.name,
      description: clean(englishText.flavor_text),
      types: [...poke.types]
        .sort((a, b) => a.slot - b.slot)
        .map((t) => t.type.name),
      height: poke.height,
      weight: poke.weight,
    });
  }

  // JSON.stringify produces a valid, fully escaped TS string literal.
  const literal = (value: string): string => JSON.stringify(value);
  const body = rows
    .map(
      (r) =>
        `  { dexId: ${r.dexId}, name: ${literal(r.name)}, description: ${literal(r.description)}, types: [${r.types.map(literal).join(', ')}], height: ${r.height}, weight: ${r.weight} },`,
    )
    .join('\n');

  const file = `/**
 * GENERATED by scripts/fetch-species.ts — do not edit by hand.
 * Source: PokeAPI (https://pokeapi.co), dex 1-151: the official English
 * name, the first English flavor text, the modern type set (current games
 * / Pokémon GO) and the size in PokeAPI raw units (dm, hg).
 * Regenerate with: npm run seed:species
 */

import type { Pokemon } from '../db';

/** All 151 Gen-1 species in dex order — the seed for the pokemon table. */
export const SPECIES: readonly Pokemon[] = [
${body}
];
`;

  await mkdir('model/seed', { recursive: true });
  await writeFile(OUT_FILE, file);
  console.log(`Wrote ${OUT_FILE} (${rows.length} species)`);
} catch (err) {
  console.error(
    `Failed: ${err instanceof Error ? err.message : String(err)} — no seed file written.`,
  );
  process.exit(1);
}

async function fetchSpecies(id: number): Promise<SpeciesJson> {
  let last: unknown;
  for (let attempt = 0; attempt < RETRIES; attempt++) {
    try {
      const res = await fetch(`${SPECIES_BASE}/${id}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return (await res.json()) as SpeciesJson;
    } catch (err) {
      last = err;
    }
  }
  throw last instanceof Error ? last : new Error(String(last));
}

async function fetchPokemon(id: number): Promise<PokemonJson> {
  let last: unknown;
  for (let attempt = 0; attempt < RETRIES; attempt++) {
    try {
      const res = await fetch(`${POKEMON_BASE}/${id}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return (await res.json()) as PokemonJson;
    } catch (err) {
      last = err;
    }
  }
  throw last instanceof Error ? last : new Error(String(last));
}

/** Flavor text is typeset for the old games — fold its line/page breaks
 *  and stray soft hyphens into one clean paragraph. */
function clean(text: string): string {
  return text
    .replace(/[\n\f­]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}
