/**
 * One-shot generator: fetch the Gen-1 species catalog from PokeAPI and
 * write model/seed/species.ts — the rows that seed the `pokemon` table.
 * The mirror of scripts/download-icons.ts (run: npm run seed:species).
 *
 * For each dexId 1..151 it takes the official English name (PokeAPI's
 * localized `names` keep the real spelling: Farfetch'd, Nidoran♀,
 * Mr. Mime) plus the first English flavor text as the description.
 * The extension itself never talks to the network — this runs once,
 * while developing, and its output is committed like the icons.
 */

import { mkdir, writeFile } from 'node:fs/promises'

const API_BASE = 'https://pokeapi.co/api/v2/pokemon-species'
const OUT_FILE = 'model/seed/species.ts'
const FIRST_ID = 1
const LAST_ID = 151
const RETRIES = 3

/** The slice of a PokeAPI pokemon-species response this script needs. */
interface SpeciesJson {
  names: { name: string; language: { name: string } }[]
  flavor_text_entries: { flavor_text: string; language: { name: string } }[]
}

interface SeedRow {
  dexId: number
  name: string
  description: string
}

try {
  const rows: SeedRow[] = []

  for (let id = FIRST_ID; id <= LAST_ID; id++) {
    const json = await fetchSpecies(id)

    const englishName = json.names.find((n) => n.language.name === 'en')
    if (!englishName) throw new Error(`#${id}: no English name in the response`)

    const englishText = json.flavor_text_entries.find((e) => e.language.name === 'en')
    if (!englishText) throw new Error(`#${id}: no English flavor text in the response`)

    rows.push({
      dexId: id,
      name: englishName.name,
      description: clean(englishText.flavor_text),
    })
  }

  // JSON.stringify produces a valid, fully escaped TS string literal.
  const literal = (value: string): string => JSON.stringify(value)
  const body = rows
    .map((r) => `  { dexId: ${r.dexId}, name: ${literal(r.name)}, description: ${literal(r.description)} },`)
    .join('\n')

  const file = `/**
 * GENERATED by scripts/fetch-species.ts — do not edit by hand.
 * Source: PokeAPI (https://pokeapi.co), dex 1-151: the official English
 * name and first English flavor text per species.
 * Regenerate with: npm run seed:species
 */

import type { Pokemon } from '../db';

/** All 151 Gen-1 species in dex order — the seed for the pokemon table. */
export const SPECIES: readonly Pokemon[] = [
${body}
];
`

  await mkdir('model/seed', { recursive: true })
  await writeFile(OUT_FILE, file)
  console.log(`Wrote ${OUT_FILE} (${rows.length} species)`)
} catch (err) {
  console.error(`Failed: ${err instanceof Error ? err.message : String(err)} — no seed file written.`)
  process.exit(1)
}

async function fetchSpecies(id: number): Promise<SpeciesJson> {
  let last: unknown
  for (let attempt = 0; attempt < RETRIES; attempt++) {
    try {
      const res = await fetch(`${API_BASE}/${id}`)
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      return (await res.json()) as SpeciesJson
    } catch (err) {
      last = err
    }
  }
  throw last instanceof Error ? last : new Error(String(last))
}

/** Flavor text is typeset for the old games — fold its line/page breaks
 *  and stray soft hyphens into one clean paragraph. */
function clean(text: string): string {
  return text.replace(/[\n\f­]/g, ' ').replace(/\s+/g, ' ').trim()
}